name: Build Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build Package
        run: |
          make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MicDefault-DEB
          path: packages/*.deb
