name: Build Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew install ldid

      - name: Setup Theos and SDKs
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          rm -rf $HOME/theos/sdks
          mkdir -p $HOME/theos/sdks
          cd $HOME/theos/sdks
          git init
          git remote add origin https://github.com/theos/sdks.git
          git sparse-checkout init --cone
          git sparse-checkout set iPhoneOS15.5.sdk
          git pull origin master --depth=1


      - name: Build Package
        env:
          THEOS: /Users/runner/theos
        run: |
          make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MicDefault-DEB
          path: packages/*.deb
